#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG_FILE="$(cat $1)"
REGEXP="(#[0-9]+)"

if [[ ! $COMMIT_MSG_FILE =~ $REGEXP ]]; then
  echo "Not permitted commit message convention"
  echo "Write valid issue number in commit message"
  exit 1
else
  exit 0
fi
